info:
  contact: {}
paths:
  /login:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - auth
  /register:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - auth
  /users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - users
    post:
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - users
  /users/:id:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - users
swagger: "2.0"
