version: '2.1'
services:
  time-tracker-database:
    image: 'postgres:alpine'
    restart: always
    ports:
      - '5444:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'time-tracker'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
