#
@base = http://localhost:3000
# @base = https://api.time-tracker.ml
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1cHU2MEBnbWFpbC5jb20iLCJleHAiOjE2MzkxNTI1MTksImlhdCI6MTYzODg5MzMxOX0.nMeKv85MOFOagopCWGkIlw0WMvNjwEpfQNzAcjgKyXM

###
POST {{base}}/register
Content-Type: application/json

{
  "user_name": "bogdan",
  "password": "bogdan123",
  "email": "lupu60@gmail.com"
}

###
POST {{base}}/login
Content-Type: application/json

{
  "email": "lupu60@gmail.com",
  "password": "bogdan123"
}


###
GET {{base}}/api/users
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{base}}/api/clients
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{base}}/api/clients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "client1",
  "projects": [{"name": "projects1"},{"name": "projects2"}]
}



###
GET {{base}}/api/users/619a8695a6e8de3abda0d312
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{base}}/api/users/619a8695a6e8de3abda0d312/projects
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "619780122fe146d80c548d3c"
}



### create worklog
###
POST {{base}}/api/users/619a8695a6e8de3abda0d312/worklog
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "project_id": "619780122fe146d80c548d3c",
  "hours":6,
  "description":"working on the register page"
}



### get worklog
