
# @base = http://localhost:3000
@base = https://api.time-tracker.ml
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1cHU2MEBnbWFpbC5jb20iLCJleHAiOjE2Mzc0Mjk1ODYsImlhdCI6MTYzNzE3MDM4Nn0.Zg4uPBZPxdXiEm8iV5IcDpM97LPiEV9LxYt5MAyNYSw

###
POST {{base}}/register
Content-Type: application/json

{
  "user_name": "bogdan",
  "password": "bogdan123",
  "email": "lupu60@gmail.com"
}

###
POST {{base}}/login
Content-Type: application/json

{
  "email": "lupu60@gmail.com",
  "password": "bogdan123"
}


###
GET {{base}}/api/users
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{base}}/api/users/userid/projects
Content-Type: application/json
Authorization: Bearer {{token}}



###
GET {{base}}/api/clients
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{base}}/api/clients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "client1",
  "projects": [{"name": "projects1"},{"name": "projects2"}]
}



### create worklog

### get worklog
