name: CI-iOS

on:
  push:
    branches: [ main, feature/test-ci ]

  pull_request:
    branches: [ develop ]
    types: [ opened, reopened ]

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-11

    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Select Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer
    
    - name: Build
      run: |
        xcodebuild build-for-testing -scheme "CI" -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" ONLY_ACTIVE_ARCH=YES | xcpretty -s || exit 1
    
    - name: Test
      run: |
        xcodebuild test-without-building -scheme "CI" -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" ONLY_ACTIVE_ARCH=YES | xcpretty -s || exit 1