name: CI-iOS

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ develop ]
    types: [ opened, reopened ]

jobs:
  build-and-test:
    runs-on: macos-11

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer
    - name: Build and Test
      run: xcodebuild clean test -workspace TimeTracker.xcworkspace -scheme "TimeTrackerClient" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" ONLY_ACTIVE_ARCH=YES | xcpretty -s

