name: Deploy-Manager

on:
  push:
    branches: [ trigger-deploy ]

jobs:
  build-and-deploy:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: GPG version
      run: gpg --version

    - name: Install provisioning profile
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.MAN_PROFILE }}" --output .github/secrets/TimeTrackerManagerProfile.mobileprovision .github/secrets/TimeTrackerManagerProfile.mobileprovision.gpg

        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles

        cp .github/secrets/TimeTrackerManagerProfile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

    - name: Install keychain certificate
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.IOS_KEYS }}" --output .github/secrets/Certificates.p12 .github/secrets/Certificates.p12.gpg

        KEYCHAIN_PATH=$RUNNER_TEMP/build.keychain

        security create-keychain -p "" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "" $KEYCHAIN_PATH
        security import .github/secrets/Certificates.p12 -P "" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build
      run: xcodebuild clean archive -sdk iphoneos -workspace TimeTracker.xcworkspace -configuration "Release" -scheme "TimeTrackerManager" -derivedDataPath "DerivedData" -archivePath "DerivedData/Archive/TimeTrackerManager.xcarchive" | xcpretty

    - name: Export
      run: xcodebuild -exportArchive -archivePath DerivedData/Archive/TimeTrackerManager.xcarchive -exportOptionsPlist .github/secrets/ExportOptionsManager.plist -exportPath DerivedData/ipa | xcpretty

    - name: Deploy
      run: xcrun altool --upload-app --type ios --file "DerivedData/ipa/TimeTrackerManager.ipa" --username "${{ secrets.APPLEID_USERNAME }}" --password "${{ secrets.APPLEID_PASSWORD }}" --verbose
